# -*- mode: ruby -*-
# vi: set ft=ruby :


VAGRANT_BOX         = "sandinv/ubuntu2004"
VAGRANT_BOX_VERSION = "0.0.2"
CPUS                = 1
MEMORY              = 4048

Vagrant.configure(2) do |config|

    config.ssh.insert_key = false
    config.vm.provision :ansible do |ansible|

      ansible.playbook = "provisioning/main.yml"
      ansible.galaxy_role_file = "provisioning/requirements.yml"
      ansible.become = true
    end

    config.vm.define "docker" do |node|

      node.vm.box               = VAGRANT_BOX
      node.vm.box_check_update  = false
      node.vm.box_version       = VAGRANT_BOX_VERSION
      node.vm.hostname          = "docker"

      node.vm.network "private_network", ip: "10.0.0.2"

      node.vm.provider :virtualbox do |v|
        v.name    = "docker"
        v.memory  = MEMORY
        v.cpus    = CPUS
      end

      node.vm.provider :libvirt do |v|
        v.memory  = MEMORY
        v.nested  = true
        v.cpus    = CPUS
      end
    end
end
