- hosts: all
  vars:
    pip_install_packages:
      - name: docker
    docker_users:
      - victor
  pre_tasks:
    - name: Ensure apt cache is update
      apt:
        update_cache: yes
  roles:
    - sandinv.credentials
    - geerlingguy.pip
    - geerlingguy.docker
  tasks:
    - name: Configure docker context in localhost
      delegate_to: localhost
      become: no
      block:
        - name: Scan for SSH host keys.
          shell:
            cmd: ssh-keyscan -trsa 10.0.0.2 2>/dev/null
          changed_when: False
          register: ssh_scan
        - name: Update known_hosts.
          known_hosts:
            key: "{{ item }}"
            name: "10.0.0.2"
          with_items: "{{ ssh_scan.stdout_lines }}"
        - name: Remove previous docker context
          shell:
            cmd: docker context rm -f remote-docker
          ignore_errors: yes
        - name: Create docker context
          shell:
            cmd: docker context create --docker host=ssh://victor@10.0.0.2 --description="Remote docker" remote-docker
        - name: Set docker context
          shell:
            cmd: docker context use remote-docker
